spring:
  application:
    name: "bus-service"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://localhost:8088"



#spring:
#application:
#name: ?bus?
#profiles:
#active: ?service?
#config: import: ?optional:configserver:http://localhost:8088?

#spring:
#  application:
#    name: "bus"
#  profiles:
#    active: "ser"
#  config:
#    import: "configserver:http://localhost:8088"

#server:
#  port: 8082
